### ISSUE TITLE
Issue: #PHP-Unit #Phinx - Error: Call to a member function hasOption() on null

### ISSUE THREAD

**Issue by Daivir** [Daivir/Framework#2]
## Errors on: 

1. Tests\App\Blog\Table\PostTableTest::testFind
2. Tests\App\Blog\Table\PostTableTest::testFindNotFoundRecord
3. Tests\App\Blog\Table\PostTableTest::testUpdate
4. Tests\App\Blog\Table\PostTableTest::testInsert
5. Tests\App\Blog\Table\PostTableTest::testDelete

### Command:
`$ ./vendor/bin/phpunit`

### Result:
```
Error: Call to a member function hasOption() on null

/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php:248
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:126
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SQLiteAdapter.php:228
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Table.php:609
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Table.php:697
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php:218
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:74
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:56
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php:71
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterFactory.php:131
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php:344
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php:261
/Users/$USER/Sites/Workspace/Framework/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:300
/Users/$USER/Sites/Workspace/Framework/tests/DatabaseTestCase.php:50
/Users/$USER/Sites/Workspace/Framework/tests/Blog/Table/PostTableTest.php:22
```

**Comment by mxmaxime** [comment]
Hi,
I have the same issue, how did you fixed this ?

Reguards,

**Comment by Daivir** [comment]
Hello!
It's a critical issue of Phinx: [#1181](https://github.com/cakephp/phinx/pull/1181).
This is supposed to be merged to the master branch but it doesn't work (for me at least), even in @dev version.
So you need to replace manually this script: [\Phinx\Db\Adapter\AbstractAdapter.php](https://codecov.io/gh/cakephp/phinx/src/4c26aeba23995cfbce16a5c7d2324abd17fc4f66/src/Phinx/Db/Adapter/AbstractAdapter.php).
You should also clean "phinxlog" in your database.

For the moment that's the only solution I've found (which is not convenient with a composer update ofc), let me know if you find a better solution.

Good luck!

**Comment by mxmaxime** [comment]
Hello!

Thanks, it worked :)

**Comment by D4rkMindz** [comment]
Hello
I already had this problem few times. The solution (every single time) was to drop and create the phinxlog table. I executed following SQL:

```SQL
DROP TABLE IF EXISTS `phinxlog`;

CREATE TABLE `phinxlog` (
  `version` BIGINT(20) NOT NULL,
  `migration_name` VARCHAR(100) DEFAULT NULL,
  `start_time` TIMESTAMP NULL DEFAULT NULL,
  `end_time` TIMESTAMP NULL DEFAULT NULL,
  `breakpoint` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`version`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
```

**Comment by Daivir** [comment]
Hi,
Personally it works for me on the Phinx dev version now :)
Thanks for the feedbacks!
